# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YaziApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiketler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(help_text='Etiketi giriniz.', max_length=40, verbose_name='Etiket')),
                ('sef', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Etiketler',
            },
        ),
        migrations.CreateModel(
            name='Yazilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(help_text='Yazının başlığını giriniz.', max_length=255, verbose_name='Yazı başlığı')),
                ('sef', models.SlugField(max_length=255)),
                ('icerik', models.TextField(help_text='Yazının içeriğini giriniz.', verbose_name='Yazı içeriği')),
                ('etiketler', models.ManyToManyField(to='YaziApp.Etiketler')),
                ('kategori', models.ForeignKey(help_text='Yazının kategorisini seçiniz.', on_delete=django.db.models.deletion.CASCADE, to='YaziApp.Kategoriler', verbose_name='Yazı kategorisi')),
                ('uye', models.ForeignKey(help_text='Yazının sahibini seçiniz.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name_plural': 'Yazılar',
            },
        ),
    ]
